# Generated by Django 5.0.6 on 2024-11-24 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_is_verified'),
        ('school', '0003_alter_maktab_maktab_raqami_alter_maktab_nomi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='maktab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.maktab', verbose_name='Maktab'),
        ),
    ]
