# Generated by Django 5.0.6 on 2024-11-24 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
