# Generated by Django 5.0.6 on 2024-11-24 19:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_filial_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Yaratilgan vaqti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='center',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi'),
        ),
        migrations.AddField(
            model_name='center',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlanganmi'),
        ),
        migrations.AddField(
            model_name='center',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti"),
        ),
        migrations.AddField(
            model_name='kasb',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kasblar', to='center.center', verbose_name='Markaz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kurs',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kurslar', to='center.center', verbose_name='Markaz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yonalish',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='yonalishlar', to='center.center', verbose_name='Markaz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='center',
            name='nomi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Markaz nomi'),
        ),
        migrations.AlterField(
            model_name='center',
            name='rahbari',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Rahbari'),
        ),
        migrations.AlterField(
            model_name='kasb',
            name='nomi',
            field=models.CharField(max_length=255, verbose_name='Kasb nomi'),
        ),
        migrations.AlterField(
            model_name='yonalish',
            name='nomi',
            field=models.CharField(max_length=255, verbose_name="Yo'nalish nomi"),
        ),
    ]
