# Generated by Django 5.0.6 on 2024-11-28 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_center_created_at_center_is_active_and_more'),
        ('school', '0003_alter_maktab_maktab_raqami_alter_maktab_nomi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiyasi')),
                ('belgisi', models.CharField(max_length=100, verbose_name='Sinf Belgisi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilingan'), ('accept_group', 'Guruhga qabul qilindi'), ('rejected', 'Rad etilgan')], default='pending', max_length=15, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan foydalanuvchi")),
                ('kasb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='center.kasb', verbose_name='Kasb')),
                ('sinf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.sinf', verbose_name='Sinf')),
                ('yonalish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='center.yonalish', verbose_name="Yo'nalish")),
            ],
        ),
    ]
