# Generated by Django 5.0.6 on 2024-11-28 11:48

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_submittedstudent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='administered_filials', to=settings.AUTH_USER_MODEL, verbose_name='Administratorlar'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Qo'shilgan vaqt"),
        ),
    ]
